### ISSUE TITLE
Tags customization

### ISSUE THREAD

**Issue by cyrakuse** [mikaeljorhult/brackets-todo#101]
We can create any tags we wan't and that's a good thing.
Maybe it could be a good idea to separate the tag name that is searched in files and the tag name displayed in the todo list.

For example, we could have this in the config file : 
    "tags": [
        { "tag-name": "TODO", "display-name": "To do", "color": "#696" },
        { "tag-name": "FUTURE", "display-name": "For Next Release", "color": "#F00" },
    ]

Then we could have a simple string to write in code to have it in todo list and in the same time we could have a good display

**Comment by mikaeljorhult** [comment]
Name and color can be specified through the `.todo` file.
