### ISSUE TITLE
Is there a way to set custom tags only for a file?

### ISSUE THREAD

**Issue by nicolo-ribaudo** [mikaeljorhult/brackets-todo#102]
I'm sorry if my question is not clever...

I would use different settings for different files.
For example, I have a .css file that should use the `/* @#TODO This is a comment */` syntax and a .js file  that should use the `// ...TODO... This is another comment` syntax...

Or is better if I use a regex that matchs both comments?

**Comment by mikaeljorhult** [comment]
Did you get this to work the way you want @nicolo-ribaudo?

**Comment by mikaeljorhult** [comment]
Closing this for now. Please reopen if it's still an issue.
