### ISSUE TITLE
Extension causes issues with file renaming

### ISSUE THREAD

**Issue by globexdesigns** [mikaeljorhult/brackets-todo#105]
See issue posted here: https://github.com/adobe/brackets/issues/10048#issuecomment-65729320

**Comment by mikaeljorhult** [comment]
Sorry for the long response time @globexdesigns. I've been looking into this and tried recreating it on my machines but with no luck, either on OS X or on Windows 8.

Which version of Brackets and Todo are you using?

**Comment by globexdesigns** [comment]
After trying it again -- I can reproduce on Brackets 1.1 on OSX with the latest version of the TODO extension from the registry. But I can also reproduce it after removing the extension. So it looks like it's not an issue with the extension after all. Please close.

**Comment by mikaeljorhult** [comment]
Are you working within Dropbox or any other synced folder? I vaguely remember something similar happening in Finder when working within Dropbox on a slow connection.

**Comment by globexdesigns** [comment]
No I'm not, but my Mac is always pegged at 98% memory usage, so it's always slow.
