### ISSUE TITLE
Release v0.8.1?

### ISSUE THREAD

**Issue by le717** [mikaeljorhult/brackets-todo#114]
You said in https://github.com/mikaeljorhult/brackets-todo/issues/110#issuecomment-70124705

> Try resetting your settings using the reset button in the lower left corner. HTML support was added in the latest release and is only used if you reset.

I hate to be the one to say this, but HTML support is only present on `master`, _not_ the latest 0.8.0 release. I just uninstall this extension then installed it from the extension manager, and HTML comments were still not detected, as verified by checking Default.js against b9cbc1adebf7f1f8dbdd07d4df885290bc7e8066. Only when I downloaded the latest code from `master` then reset the settings was the HTML comment detected.

Can you perhaps bump the version and release the code as it stands right now to the extension manager? You'd save yourself and others a lot of typing about why x new feature is not available although it _is_ present, but only from GitHub directly? :)

**Comment by mikaeljorhult** [comment]
Thank you for pushing me on this and sorry for not getting back to you sooner. Been a busy couple of months.

I will release 0.8.1 in a couple of minutes. I hope it will make things easier for you.

**Comment by mikaeljorhult** [comment]
Well, as soon as the Backets extension registry will allow me to...

**Comment by le717** [comment]
Is it the "BAD REQUEST"

**Comment by mikaeljorhult** [comment]
Yes, I've been getting a couple of different error messages since yesterday. I've reported it in the newly opened issue so it'll probably be solved soon.

**Comment by mikaeljorhult** [comment]
@le717 Just to let you know - the registry just let me upload the 0.8.1 version.

**Comment by le717** [comment]
Thanks for letting me know. :)
