### ISSUE TITLE
how often does todo list get updated?

### ISSUE THREAD

**Issue by nadranaj** [mikaeljorhult/brackets-todo#121]
I add "TODO" or "NOTE" keywords in my text file. But it takes some indefinite time (like 5 to 10 mins) for that to appear in TODO window down. Is there any refresh interval / timer? I do not see the TODO or NOTE comments reflecting as TODO instantly.

**Comment by mikaeljorhult** [comment]
It's displayed as soon as you save the file.

**Comment by iammarix** [comment]
They only seem to display if I switch which file I'm editing, and then switch back. Is there a command to force an update?

**Comment by cosmicduststorm** [comment]
I can't even get them to display when I switch between what files I'm editing, or even if I close the file and reopen it. The only way I have been able to consistently get the list to update is when I close Brackets and relaunch the program. Even then, the list can just vanish and won't reappear until I close and relaunch again.

**Comment by agodlydeciple** [comment]
I am having a similar issue where I need to open the settings and close it and then they will appear, otherwise they never show up.

**Comment by mikaeljorhult** [comment]
The way updates are handled have changed a lot in the upcoming version 0.9.0. It should make updating a bit faster. Feel free to check out the pre-release branch (d6e7bf8c009c8060572744298bf83c4914d7d22a).
