### ISSUE TITLE
.git/COMMIT_EDITMSG shown in TODO-list

### ISSUE THREAD

**Issue by hacker112** [mikaeljorhult/brackets-todo#123]
When try to commit with git the .git/COMMIT_EDITMSG is shown in brackets-TODO:s

![skarmklipp 2015-10-30 11 43 01](https://cloud.githubusercontent.com/assets/620746/10843800/68a231bc-7efb-11e5-8d4d-26fc8efa3df8.png)

It does not help to add the them to excluded folders/files in brackets-todo settings

**Comment by mikaeljorhult** [comment]
I'm not able to recreate this. Please try the latest version of the extension.
