### ISSUE TITLE
Hide Ticked Todos

### ISSUE THREAD

**Issue by Klustre** [mikaeljorhult/brackets-todo#124]
When I tick a todo [x] it now becomes inactive with the text struck through. It would be nice if it would disappear into another group that you can show/hide. This way you can see the todos become less which is good for the stress levels and they don't clog the interface.

**Comment by mikaeljorhult** [comment]
This is possible through a setting in the upcoming version 0.9.0. Feel free to check out the pre-release branch (d6e7bf8c009c8060572744298bf83c4914d7d22a).
