### ISSUE TITLE
sprite.svg is requested every time document is saved

### ISSUE THREAD

**Issue by petetnt** [mikaeljorhult/brackets-todo#125]
Minor issue, but `sprite.svg` is being requested every time document is being saved.

![image](https://cloud.githubusercontent.com/assets/7641760/12004151/f9719d1a-ab4a-11e5-8a3a-289473f98e64.png)

**Comment by mikaeljorhult** [comment]
This is addressed in the upcoming version 0.9.0. Feel free to check out the pre-release branch (d6e7bf8c009c8060572744298bf83c4914d7d22a).
