### ISSUE TITLE
Global Mustache is deprecated

### ISSUE THREAD

**Issue by ficristo** [mikaeljorhult/brackets-todo#129]
There are some deprecation warnings raised like this:
`Use brackets.getModule("thirdparty/mustache/mustache") instead of global Mustache.`
Could you fix them?

**Comment by anephew** [comment]
Just need to add:

`Mustache   = brackets.getModule("thirdparty/mustache/mustache");`

**Comment by mikaeljorhult** [comment]
This is now in the current master and will be released with the next version of the extension.

**Comment by ficristo** [comment]
Thank you.
