### ISSUE TITLE
Brackets 1.7

### ISSUE THREAD

**Issue by FlexFM** [mikaeljorhult/brackets-todo#130]
Hi,

For some reason every time Brackets is closed an re-opened todo is disabled? Can't use Brackets 1.8 due to unstable an won't run on my machine.

tried removing closing Brackets restarting pc an reinstalling todo but no luck.

any ideas?

**Comment by mikaeljorhult** [comment]
I'm haven't been able to recreate this issue. Have you tried Brackets 1.9?

**Comment by mikaeljorhult** [comment]
Please reopen this if you're still experiencing this using current version of Brackets and the extension.
