### ISSUE TITLE
release for vscode

### ISSUE THREAD

**Issue by Dragonxero** [mikaeljorhult/brackets-todo#133]
I have been using brackets since 1.4 and this TODO extension showed me a friend since then i use it in every project, but now i have to use netCore for some new project and i cant find and extension on vscode that can do what your can so i ask if there and way to release on vscode too.

**Comment by mikaeljorhult** [comment]
I've looked into how extensions for VS Code are written and there isn't much overlap with how extensions for Brackets work. Since I don't use VS Code myself I would have a hard time maintaining it so I don't see a release any time soon.
