### ISSUE TITLE
"Expand / Collapse All" removed?

### ISSUE THREAD

**Issue by eviltreehouse** [mikaeljorhult/brackets-todo#135]
Was the removal of the "Expand/Collapse All" toolbar buttons intentional during your recent refactor? I didn't see any mention of it in the `CHANGELOG`  😕 I (perhaps problematically) maintain my TODOs in a separate cluster of context-separated files so I tend to make heavy use of those buttons 😄

**Comment by mikaeljorhult** [comment]
I wanted to get the new version out and decided to wait with the expand and collapse buttons. Will be in the next version.

**Comment by mikaeljorhult** [comment]
Version 0.9.2 was just released and solves this.
