### ISSUE TITLE
use of future reserved word

### ISSUE THREAD

**Issue by blueorange589** [mikaeljorhult/brackets-todo#136]
extension was not working due to error 'use of future reserved word...' on fileUtils.js 36 and 54
simply nothing displayed in extension window

I changed lines as below
line 36
`var len = settings.search.excludeFolders.length;
  for (i=0; i < len; i++) { `
line54
`var lgth = settings.search.excludeFiles.length
 for (i = 0; i < lgth; i++) {`

now extension works, no problems

**Comment by mikaeljorhult** [comment]
Which platform (Windows, macOS, Linux) and which version of Brackets are you seeing this on? I'm not seeing this on my machines so would like to look in to it.

Would you mind creating a pull request with the changes?

**Comment by blueorange589** [comment]
I am on Ubuntu 14.04 with Brackets 1.9.0-17312
I will create a pull request.

Now extension works, but some features throwing errors like ones below
TypeError: Object [object Array] has no method 'findIndex' Files.js 230
Uncaught TypeError: Cannot read property 'length' of undefined Files.js 65
Uncaught TypeError: Object [object Array] has no method 'find' Files.js 182
Uncaught TypeError: Object [object Array] has no method 'find'  Tags.js 71

Both Brackets and brackets-todo are fresh install, with only modifications given in first post

**Comment by mikaeljorhult** [comment]
I've merged your pull request and will release the new version as soon as I've investigated the find/findIndex issue.

Thank you for your help!

**Comment by blueorange589** [comment]
Thanks, I will be looking for the new version. Very nice extension, btw.
