### ISSUE TITLE
Todo won't install on Brackets 1.11

### ISSUE THREAD

**Issue by BrianIsSecond** [mikaeljorhult/brackets-todo#148]
<img width="755" alt="napkin 39 09-26-17 7 07 11 pm" src="https://user-images.githubusercontent.com/13523868/30888349-14e362f8-a2ee-11e7-86d4-736b88375374.png">

**Comment by BrianIsSecond** [comment]
I've tried on 2 computers so far... same result. Manual install works fine.

**Comment by BrianIsSecond** [comment]
P.S. Great Plugin! Love it!

**Comment by mikaeljorhult** [comment]
Thank you for reporting it. It's a known issue due to the move from React to Preact library. The new version is ready and I'm doing testing on the released version this evening.

If you want to get going now you can grab the latest master branch.

**Comment by mikaeljorhult** [comment]
@BrianIsSecond Version 0.9.6 is now released and should work fine with Brackets 1.11. Please let me know if you run into any issues.

**Comment by BrianIsSecond** [comment]
Thanks so much! Seriously, I can't thank you enough for creating this extension. Be encouraged! You're doing great work!

In Christ,
Brian

**Comment by mikaeljorhult** [comment]
Thank you for your kind words! I'm glad you find it useful.
