### ISSUE TITLE
Optimize display

### ISSUE THREAD

**Issue by cyrakuse** [mikaeljorhult/brackets-todo#99]
TODO display a list of files and in each file we see the list of todo.
Maybe it could be better to see a list of todo and for each the possibility to deploy it to see the concerning file.
Here is an image that show this :
![capture](https://cloud.githubusercontent.com/assets/3593751/4609796/dae4a9f4-52a5-11e4-9b12-6e0ab35afe55.PNG)

**Comment by mikaeljorhult** [comment]
Will keep it as is for now for clean code.
